# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{be_valid_asset}
  s.version = "1.1.2"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Alex Tomlins", "Sebastian de Castelberg", "Ben Brinckerhoff"]
  s.date = %q{2011-09-03}
  s.description = %q{Provides be_valid_xhtml, be_valid_css and be_valid_feed matchers for rspec controller and view tests.}
  s.email = %q{github@unboxedconsulting.com}
  s.extra_rdoc_files = [
    "README.markdown"
  ]
  s.files = [
    "MIT-LICENSE.txt",
    "README.markdown",
    "Rakefile",
    "lib/be_valid_asset.rb",
    "lib/be_valid_asset/be_valid_base.rb",
    "lib/be_valid_asset/be_valid_css.rb",
    "lib/be_valid_asset/be_valid_feed.rb",
    "lib/be_valid_asset/be_valid_xhtml.rb",
    "spec/be_valid_asset/be_valid_css_spec.rb",
    "spec/be_valid_asset/be_valid_feed_spec.rb",
    "spec/be_valid_asset/be_valid_xhtml_spec.rb",
    "spec/files/invalid.css",
    "spec/files/invalid.html",
    "spec/files/invalid2.html",
    "spec/files/invalid_feed.xml",
    "spec/files/valid-1.css",
    "spec/files/valid-2.css",
    "spec/files/valid-3.css",
    "spec/files/valid.css",
    "spec/files/valid.html",
    "spec/files/valid_feed.xml",
    "spec/spec.opts",
    "spec/spec_helper.rb"
  ]
  s.homepage = %q{http://github.com/unboxed/be_valid_asset}
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.7}
  s.summary = %q{Markup validation for RSpec}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<rspec>, [">= 0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
    else
      s.add_dependency(%q<rspec>, [">= 0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    end
  else
    s.add_dependency(%q<rspec>, [">= 0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
  end
end

